# Generated by Django 6.0 on 2026-01-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_collection_created_at_collection_is_active_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='stock_never_negative'),
        ),
    ]
