# Generated by Django 6.0 on 2026-01-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='client_secret',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
