# Generated by Django 6.0 on 2026-01-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_paymenttransaction_client_secret'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymenttransaction',
            name='unique_payment_per_order_gateway',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='inventory_locked',
        ),
        migrations.AddField(
            model_name='order',
            name='refund_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_restored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAID', 'Paid'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCEL_REQUESTED', 'Cancel Requested'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='CREATED', max_length=30),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='client_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
